services:
  calibre:
    image: linuxserver/calibre
    container_name: calibre
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - data:/config
    ports:
      - 8080:8080
      - 8081:8081

  ftp-server:
    image: garethflowers/ftp-server
    container_name: ftp-server
    restart: unless-stopped
    environment:
      - FTP_USER=user
      - FTP_PASS=123456
    ports:
      - "20-21:20-21/tcp"
      - "40000-40009:40000-40009/tcp"
    volumes:
      - data:/home/user
volumes:
  data: null
