name: cloudflare-pages

on:
  push:
    paths:
      - "docs/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 8195e492899a70fc09df5df7049e7410
          projectName: mobikarl
          directory: site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
