name: sync-code
on:
  push:
    paths:
      - "docs/**"

jobs:
  gitlab:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      # 在$GITHUB_WORKSPACE目录下检出git仓库，供job访问使用
      - uses: actions/checkout@v2
      - name: sync
        run: |
          git remote -v
          # 必须指定unshallow参数，否则后续推送会报错
          git fetch --unshallow origin

          echo "============使用gitlab密码来推送git仓库============"
          git remote add remote https://mobikarl:${{ secrets.GITLAB_PASSWORD }}@gitlab.com/mobikarl/mobikarl.git
          git push --all --force remote
